// ── PBQ Metadata Registry ──────────────────────────────────────────
// Separate from components to avoid dynamic+static import conflicts

import type { PBQMetadata } from './shared/types';

export const PBQ_METADATA: PBQMetadata[] = [
  {
    id: 'network-topology',
    title: 'Network Topology Analyzer',
    description: 'Analyze a live network topology, identify vulnerable nodes, and trace the optimal attack path through routers, firewalls, and hosts.',
    difficulty: 3,
    category: 'PenTest+',
    tags: ['network', 'recon', 'path-tracing'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'terminal-sim',
    title: 'Interactive Terminal',
    description: 'Navigate a realistic terminal simulation. Run nmap scans, interpret output, and select the correct exploit path to compromise the target.',
    difficulty: 3,
    category: 'PenTest+',
    tags: ['terminal', 'nmap', 'exploitation'],
    xpReward: 60,
    estimatedTime: '10 min',
  },
  {
    id: 'web-vuln-hotspot',
    title: 'Web Vulnerability Scanner',
    description: 'Inspect a mock web application to identify 5 common security vulnerabilities hidden in forms, URLs, headers, and code.',
    difficulty: 2,
    category: 'Security+',
    tags: ['web', 'vulnerabilities', 'appsec'],
    xpReward: 40,
    estimatedTime: '6 min',
  },
  {
    id: 'firewall-rules',
    title: 'Firewall Rule Architect',
    description: 'Drag and drop firewall rules into the correct priority order, then watch packets flow through and validate your configuration.',
    difficulty: 4,
    category: 'Security+',
    tags: ['firewall', 'rules', 'network-security'],
    xpReward: 55,
    estimatedTime: '10 min',
  },
  {
    id: 'cert-chain',
    title: 'Certificate Chain Validator',
    description: 'Analyze a TLS certificate chain. Identify expired certificates, mismatched CNs, and untrusted roots by inspecting each cert in the hierarchy.',
    difficulty: 3,
    category: 'Security+',
    tags: ['crypto', 'tls', 'certificates'],
    xpReward: 45,
    estimatedTime: '7 min',
  },
  {
    id: 'log-radar',
    title: 'Log Analysis Radar',
    description: 'Analyze streaming log entries to detect attack patterns. Flag suspicious entries and correlate events on the timeline radar.',
    difficulty: 4,
    category: 'Security+',
    tags: ['logs', 'siem', 'threat-detection'],
    xpReward: 55,
    estimatedTime: '10 min',
  },
  {
    id: 'wireless-attack',
    title: 'Wireless Attack Visualizer',
    description: 'Simulate a wireless network assessment. Place attack tools, capture the WPA handshake, and crack the password through a visual interactive flow.',
    difficulty: 3,
    category: 'PenTest+',
    tags: ['wireless', 'wpa2', 'aircrack'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'exploit-chain',
    title: 'Exploit Chain Builder',
    description: 'Construct a multi-step exploit chain against a target system. Progress from reconnaissance to full system compromise through correct technique selection.',
    difficulty: 5,
    category: 'PenTest+',
    tags: ['exploitation', 'privesc', 'lateral-movement'],
    xpReward: 70,
    estimatedTime: '12 min',
  },
  {
    id: 'subnet-calculator',
    title: 'Subnet Calculator Challenge',
    description: 'Calculate subnet masks, network addresses, broadcast addresses, and usable host ranges for increasingly complex scenarios.',
    difficulty: 3,
    category: 'Network+',
    tags: ['subnetting', 'ipv4', 'cidr', 'addressing'],
    xpReward: 55,
    estimatedTime: '12 min',
  },
  {
    id: 'protocol-analyzer',
    title: 'Protocol Analyzer Lab',
    description: 'Analyze packet captures to identify protocols, flags, endpoints, and anomalies across TCP, DNS, HTTP, ARP, and ICMP traffic.',
    difficulty: 3,
    category: 'Network+',
    tags: ['packet-capture', 'wireshark', 'protocols', 'analysis'],
    xpReward: 55,
    estimatedTime: '10 min',
  },
  {
    id: 'dns-resolution',
    title: 'DNS Resolution Tracer',
    description: 'Trace DNS queries from client through recursive resolver, root servers, TLD servers, and authoritative nameservers.',
    difficulty: 3,
    category: 'Network+',
    tags: ['dns', 'resolution', 'nameservers', 'records'],
    xpReward: 50,
    estimatedTime: '10 min',
  },
  {
    id: 'vlan-config',
    title: 'VLAN Configuration Lab',
    description: 'Configure VLANs on a managed switch by assigning ports, configuring trunk links, and setting native VLANs for network segmentation.',
    difficulty: 3,
    category: 'Network+',
    tags: ['vlan', 'switch', 'trunking', '802.1q'],
    xpReward: 55,
    estimatedTime: '12 min',
  },
  {
    id: 'cable-tester',
    title: 'Network Cable Tester',
    description: 'Identify cable types, connector types, and wiring standards. Troubleshoot cabling issues and select the right cable for each scenario.',
    difficulty: 2,
    category: 'Network+',
    tags: ['cabling', 'rj45', 'ethernet', 'wiring'],
    xpReward: 45,
    estimatedTime: '8 min',
  },
  {
    id: 'routing-table',
    title: 'Routing Table Engineer',
    description: 'Analyze routing tables, add static routes, identify next hops, configure default routes, and troubleshoot routing issues.',
    difficulty: 4,
    category: 'Network+',
    tags: ['routing', 'static-routes', 'next-hop', 'gateway'],
    xpReward: 60,
    estimatedTime: '12 min',
  },
];

export const CATEGORY_CONFIG: Record<string, { color: string; icon: string }> = {
  'PenTest+': { color: '#ff3366', icon: 'Target' },
  'Security+': { color: '#00ff41', icon: 'Shield' },
  'Network+': { color: '#00d4ff', icon: 'Network' },
  'A+': { color: '#2ec4b6', icon: 'Cpu' },
  'Linux LPI-1': { color: '#fb8500', icon: 'Terminal' },
  'Linux+': { color: '#ff9500', icon: 'Monitor' },
  'CySA+': { color: '#e63946', icon: 'Search' },
  'CASP+': { color: '#06d6a0', icon: 'Building' },
  'Cloud+': { color: '#00b4d8', icon: 'Cloud' },
};

export const PBQ_ACCENT_COLORS: Record<string, string> = {
  'network-topology': '#00d4ff',
  'terminal-sim': '#00ff41',
  'web-vuln-hotspot': '#a855f7',
  'firewall-rules': '#ffaa00',
  'cert-chain': '#00d4ff',
  'log-radar': '#ff3366',
  'wireless-attack': '#00e5ff',
  'exploit-chain': '#ff3366',
  'subnet-calculator': '#00d4ff',
  'protocol-analyzer': '#00d4ff',
  'dns-resolution': '#00d4ff',
  'vlan-config': '#00d4ff',
  'cable-tester': '#00d4ff',
  'routing-table': '#00d4ff',
};

export const PBQ_ICONS: Record<string, string> = {
  'network-topology': 'Network',
  'terminal-sim': 'Terminal',
  'web-vuln-hotspot': 'Globe',
  'firewall-rules': 'ShieldCheck',
  'cert-chain': 'Lock',
  'log-radar': 'Activity',
  'wireless-attack': 'Wifi',
  'exploit-chain': 'Target',
  'subnet-calculator': 'Calculator',
  'protocol-analyzer': 'Search',
  'dns-resolution': 'Globe',
  'vlan-config': 'Layers',
  'cable-tester': 'Cable',
  'routing-table': 'GitBranch',
};
