// ── PBQ Metadata Registry ──────────────────────────────────────────
// Separate from components to avoid dynamic+static import conflicts

import type { PBQMetadata } from './shared/types';

export const PBQ_METADATA: PBQMetadata[] = [
  {
    id: 'network-topology',
    title: 'Network Topology Analyzer',
    description: 'Analyze a live network topology, identify vulnerable nodes, and trace the optimal attack path through routers, firewalls, and hosts.',
    difficulty: 3,
    category: 'PenTest+',
    tags: ['network', 'recon', 'path-tracing'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'terminal-sim',
    title: 'Interactive Terminal',
    description: 'Navigate a realistic terminal simulation. Run nmap scans, interpret output, and select the correct exploit path to compromise the target.',
    difficulty: 3,
    category: 'PenTest+',
    tags: ['terminal', 'nmap', 'exploitation'],
    xpReward: 60,
    estimatedTime: '10 min',
  },
  {
    id: 'web-vuln-hotspot',
    title: 'Web Vulnerability Scanner',
    description: 'Inspect a mock web application to identify 5 common security vulnerabilities hidden in forms, URLs, headers, and code.',
    difficulty: 2,
    category: 'Security+',
    tags: ['web', 'vulnerabilities', 'appsec'],
    xpReward: 40,
    estimatedTime: '6 min',
  },
  {
    id: 'firewall-rules',
    title: 'Firewall Rule Architect',
    description: 'Drag and drop firewall rules into the correct priority order, then watch packets flow through and validate your configuration.',
    difficulty: 4,
    category: 'Security+',
    tags: ['firewall', 'rules', 'network-security'],
    xpReward: 55,
    estimatedTime: '10 min',
  },
  {
    id: 'cert-chain',
    title: 'Certificate Chain Validator',
    description: 'Analyze a TLS certificate chain. Identify expired certificates, mismatched CNs, and untrusted roots by inspecting each cert in the hierarchy.',
    difficulty: 3,
    category: 'Security+',
    tags: ['crypto', 'tls', 'certificates'],
    xpReward: 45,
    estimatedTime: '7 min',
  },
  {
    id: 'log-radar',
    title: 'Log Analysis Radar',
    description: 'Analyze streaming log entries to detect attack patterns. Flag suspicious entries and correlate events on the timeline radar.',
    difficulty: 4,
    category: 'Security+',
    tags: ['logs', 'siem', 'threat-detection'],
    xpReward: 55,
    estimatedTime: '10 min',
  },
  {
    id: 'wireless-attack',
    title: 'Wireless Attack Visualizer',
    description: 'Simulate a wireless network assessment. Place attack tools, capture the WPA handshake, and crack the password through a visual interactive flow.',
    difficulty: 3,
    category: 'PenTest+',
    tags: ['wireless', 'wpa2', 'aircrack'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'exploit-chain',
    title: 'Exploit Chain Builder',
    description: 'Construct a multi-step exploit chain against a target system. Progress from reconnaissance to full system compromise through correct technique selection.',
    difficulty: 5,
    category: 'PenTest+',
    tags: ['exploitation', 'privesc', 'lateral-movement'],
    xpReward: 70,
    estimatedTime: '12 min',
  },
  {
    id: 'sql-injection',
    title: 'SQL Injection Attack Lab',
    description: 'Identify vulnerable parameters, craft injection payloads, bypass authentication, extract database schemas, and escalate privileges through SQL injection.',
    difficulty: 4,
    category: 'PenTest+',
    tags: ['sql-injection', 'web-attacks', 'database', 'exploitation'],
    xpReward: 60,
    estimatedTime: '10 min',
  },
  {
    id: 'social-engineering',
    title: 'Phishing Detection Lab',
    description: 'Analyze realistic emails to identify phishing attempts. Detect spoofed domains, BEC scams, and social engineering indicators.',
    difficulty: 3,
    category: 'PenTest+',
    tags: ['phishing', 'social-engineering', 'email-security'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'incident-response',
    title: 'Incident Response Simulation',
    description: 'Walk through the NIST SP 800-61 incident response lifecycle from preparation to lessons learned with real-time threat level tracking.',
    difficulty: 4,
    category: 'Security+',
    tags: ['incident-response', 'nist', 'security-operations'],
    xpReward: 55,
    estimatedTime: '10 min',
  },
  {
    id: 'access-control',
    title: 'Access Control Configuration Lab',
    description: 'Configure RBAC assignments, enforce least privilege, set up MFA policies, implement separation of duties, and audit access logs.',
    difficulty: 3,
    category: 'Security+',
    tags: ['access-control', 'rbac', 'mfa', 'least-privilege'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'subnet-calculator',
    title: 'Subnet Calculator Challenge',
    description: 'Calculate subnet masks, network addresses, broadcast addresses, and usable host ranges for increasingly complex scenarios.',
    difficulty: 3,
    category: 'Network+',
    tags: ['subnetting', 'ipv4', 'cidr', 'addressing'],
    xpReward: 55,
    estimatedTime: '12 min',
  },
  {
    id: 'protocol-analyzer',
    title: 'Protocol Analyzer Lab',
    description: 'Analyze packet captures to identify protocols, flags, endpoints, and anomalies across TCP, DNS, HTTP, ARP, and ICMP traffic.',
    difficulty: 3,
    category: 'Network+',
    tags: ['packet-capture', 'wireshark', 'protocols', 'analysis'],
    xpReward: 55,
    estimatedTime: '10 min',
  },
  {
    id: 'dns-resolution',
    title: 'DNS Resolution Tracer',
    description: 'Trace DNS queries from client through recursive resolver, root servers, TLD servers, and authoritative nameservers.',
    difficulty: 3,
    category: 'Network+',
    tags: ['dns', 'resolution', 'nameservers', 'records'],
    xpReward: 50,
    estimatedTime: '10 min',
  },
  {
    id: 'vlan-config',
    title: 'VLAN Configuration Lab',
    description: 'Configure VLANs on a managed switch by assigning ports, configuring trunk links, and setting native VLANs for network segmentation.',
    difficulty: 3,
    category: 'Network+',
    tags: ['vlan', 'switch', 'trunking', '802.1q'],
    xpReward: 55,
    estimatedTime: '12 min',
  },
  {
    id: 'cable-tester',
    title: 'Network Cable Tester',
    description: 'Identify cable types, connector types, and wiring standards. Troubleshoot cabling issues and select the right cable for each scenario.',
    difficulty: 2,
    category: 'Network+',
    tags: ['cabling', 'rj45', 'ethernet', 'wiring'],
    xpReward: 45,
    estimatedTime: '8 min',
  },
  {
    id: 'routing-table',
    title: 'Routing Table Engineer',
    description: 'Analyze routing tables, add static routes, identify next hops, configure default routes, and troubleshoot routing issues.',
    difficulty: 4,
    category: 'Network+',
    tags: ['routing', 'static-routes', 'next-hop', 'gateway'],
    xpReward: 60,
    estimatedTime: '12 min',
  },
  // ── A+ PBQs ──
  {
    id: 'hardware-diag',
    title: 'Hardware Diagnostics Lab',
    description: 'Diagnose beep codes, POST errors, overheating, power failures, and BSOD crashes through systematic hardware troubleshooting.',
    difficulty: 2,
    category: 'A+',
    tags: ['hardware', 'diagnostics', 'post', 'troubleshooting'],
    xpReward: 40,
    estimatedTime: '8 min',
  },
  {
    id: 'os-troubleshoot',
    title: 'OS Troubleshooting Simulator',
    description: 'Troubleshoot BSOD errors, boot failures, slow performance, driver conflicts, and Windows Update issues in realistic scenarios.',
    difficulty: 2,
    category: 'A+',
    tags: ['os', 'windows', 'troubleshooting', 'bsod'],
    xpReward: 40,
    estimatedTime: '8 min',
  },
  {
    id: 'bios-config',
    title: 'BIOS/UEFI Configuration Lab',
    description: 'Configure boot order, Secure Boot, virtualization settings, BIOS passwords, and performance tuning in a simulated BIOS interface.',
    difficulty: 3,
    category: 'A+',
    tags: ['bios', 'uefi', 'firmware', 'boot-config'],
    xpReward: 45,
    estimatedTime: '8 min',
  },
  {
    id: 'disk-management',
    title: 'Disk Management Console',
    description: 'Manage partitions for dual-boot setups, resize volumes, configure RAID arrays, and recover from disk failures.',
    difficulty: 3,
    category: 'A+',
    tags: ['disk', 'partition', 'raid', 'storage'],
    xpReward: 45,
    estimatedTime: '10 min',
  },
  {
    id: 'mobile-repair',
    title: 'Mobile Device Repair Lab',
    description: 'Diagnose and fix mobile device issues including battery drain, Wi-Fi problems, cracked screens, malware, and email sync failures.',
    difficulty: 2,
    category: 'A+',
    tags: ['mobile', 'repair', 'ios', 'android'],
    xpReward: 40,
    estimatedTime: '8 min',
  },
  {
    id: 'print-troubleshoot',
    title: 'Printer Troubleshooting Lab',
    description: 'Troubleshoot printer issues including paper jams, print quality problems, network printing, drivers, and spooler crashes.',
    difficulty: 2,
    category: 'A+',
    tags: ['printer', 'troubleshooting', 'network-printing'],
    xpReward: 40,
    estimatedTime: '8 min',
  },
  // ── LPI-1 PBQs ──
  {
    id: 'file-permissions',
    title: 'Linux File Permissions Lab',
    description: 'Master chmod and chown with interactive terminal input. Practice both symbolic and octal permission notation on real file scenarios.',
    difficulty: 3,
    category: 'Linux LPI-1',
    tags: ['permissions', 'chmod', 'chown', 'linux'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'package-manager',
    title: 'Package Management Console',
    description: 'Manage packages across Debian (apt), RHEL (yum), and Fedora (dnf) distributions with distro-specific commands and workflows.',
    difficulty: 3,
    category: 'Linux LPI-1',
    tags: ['apt', 'yum', 'dnf', 'package-management'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'process-manager',
    title: 'Process Management Console',
    description: 'Manage Linux processes using kill, renice, job control, zombie cleanup, and ps with interactive process tables.',
    difficulty: 3,
    category: 'Linux LPI-1',
    tags: ['processes', 'kill', 'ps', 'job-control'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'shell-script',
    title: 'Shell Scripting Challenges',
    description: 'Write bash scripts with for loops, conditionals, pipes, parameter expansion, and functions in an interactive code editor.',
    difficulty: 4,
    category: 'Linux LPI-1',
    tags: ['bash', 'scripting', 'shell', 'automation'],
    xpReward: 55,
    estimatedTime: '10 min',
  },
  {
    id: 'user-management',
    title: 'User & Group Administration',
    description: 'Create users, manage group memberships, lock accounts, configure service accounts, and understand /etc/passwd structure.',
    difficulty: 3,
    category: 'Linux LPI-1',
    tags: ['useradd', 'usermod', 'groups', 'accounts'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'system-logs',
    title: 'System Log Analysis Lab',
    description: 'Analyze system logs to detect SSH brute force, disk SMART failures, service crash loops, privilege escalation, and OOM killer events.',
    difficulty: 4,
    category: 'Linux LPI-1',
    tags: ['syslog', 'journalctl', 'log-analysis', 'security'],
    xpReward: 55,
    estimatedTime: '10 min',
  },
  // ── Linux+ PBQs ──
  {
    id: 'kernel-module',
    title: 'Kernel Module Manager',
    description: 'Manage Linux kernel modules by loading, unloading, inspecting, and configuring them using lsmod, modprobe, modinfo, rmmod, and /etc/modules.',
    difficulty: 3,
    category: 'Linux+',
    tags: ['kernel', 'modules', 'modprobe', 'lsmod', 'drivers'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'lvm-storage',
    title: 'LVM Storage Manager',
    description: 'Manage Logical Volume Manager storage including physical volumes, volume groups, logical volumes, extending, and snapshots.',
    difficulty: 4,
    category: 'Linux+',
    tags: ['lvm', 'storage', 'pvcreate', 'vgcreate', 'lvcreate'],
    xpReward: 55,
    estimatedTime: '9 min',
  },
  {
    id: 'systemd-service',
    title: 'Systemd Service Manager',
    description: 'Manage systemd services, unit files, targets, timers, and use journalctl for log analysis in Linux environments.',
    difficulty: 3,
    category: 'Linux+',
    tags: ['systemd', 'systemctl', 'services', 'journalctl', 'timers'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'linux-firewall',
    title: 'Linux Firewall Configuration',
    description: 'Configure Linux firewalls using iptables and nftables rules, chains, policies, NAT, and port forwarding.',
    difficulty: 4,
    category: 'Linux+',
    tags: ['iptables', 'nftables', 'firewall', 'netfilter', 'security'],
    xpReward: 55,
    estimatedTime: '9 min',
  },
  {
    id: 'container-lab',
    title: 'Container Management Lab',
    description: 'Manage containers with Docker: build images, run containers, configure networking, manage volumes, and orchestrate with compose.',
    difficulty: 3,
    category: 'Linux+',
    tags: ['docker', 'containers', 'compose', 'volumes', 'networking'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'linux-network-config',
    title: 'Network Interface Configuration',
    description: 'Configure Linux network interfaces using ip, nmcli, /etc/network/interfaces, DNS resolution, and NIC bonding.',
    difficulty: 3,
    category: 'Linux+',
    tags: ['networking', 'ip', 'nmcli', 'dns', 'bonding'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  // ── CySA+ PBQs ──
  {
    id: 'siem-dashboard',
    title: 'SIEM Dashboard Analysis',
    description: 'Analyze SIEM dashboard alerts, correlate security events, identify attack patterns, and prioritize incident response actions.',
    difficulty: 3,
    category: 'CySA+',
    tags: ['siem', 'alerts', 'correlation', 'monitoring', 'log-analysis'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'threat-intel',
    title: 'Threat Intelligence Analysis',
    description: 'Analyze threat intelligence data including IOCs, STIX/TAXII feeds, threat actor attribution, and indicator correlation.',
    difficulty: 4,
    category: 'CySA+',
    tags: ['threat-intel', 'ioc', 'stix', 'taxii', 'attribution'],
    xpReward: 55,
    estimatedTime: '9 min',
  },
  {
    id: 'malware-analysis',
    title: 'Malware Analysis Lab',
    description: 'Analyze malware samples through static analysis, behavioral indicators, hash lookups, sandbox results, and classification techniques.',
    difficulty: 4,
    category: 'CySA+',
    tags: ['malware', 'static-analysis', 'sandbox', 'reverse-engineering', 'ioc'],
    xpReward: 55,
    estimatedTime: '9 min',
  },
  {
    id: 'vuln-scanner',
    title: 'Vulnerability Scanner Analysis',
    description: 'Analyze vulnerability scanner output, interpret CVE data, assess severity ratings, and prioritize remediation actions.',
    difficulty: 3,
    category: 'CySA+',
    tags: ['vulnerability', 'cve', 'cvss', 'scanning', 'remediation'],
    xpReward: 50,
    estimatedTime: '8 min',
  },
  {
    id: 'ir-timeline',
    title: 'Incident Response Timeline',
    description: 'Reconstruct incident response timelines by ordering events chronologically and identifying MITRE ATT&CK kill chain stages.',
    difficulty: 4,
    category: 'CySA+',
    tags: ['incident-response', 'timeline', 'kill-chain', 'mitre-attack', 'forensics'],
    xpReward: 55,
    estimatedTime: '9 min',
  },
  {
    id: 'forensics',
    title: 'Digital Forensics Lab',
    description: 'Perform digital forensics tasks including evidence collection, chain of custody, disk imaging, memory analysis, and artifact recovery.',
    difficulty: 4,
    category: 'CySA+',
    tags: ['forensics', 'evidence', 'chain-of-custody', 'disk-imaging', 'memory-analysis'],
    xpReward: 55,
    estimatedTime: '9 min',
  },
  // ── CASP+ PBQs ──
  {
    id: 'risk-matrix',
    title: 'Risk Assessment Matrix',
    description: 'Classify risks by likelihood and impact, calculate risk scores, and recommend appropriate mitigations across enterprise scenarios.',
    difficulty: 4,
    category: 'CASP+',
    tags: ['risk-assessment', 'risk-matrix', 'mitigation'],
    xpReward: 60,
    estimatedTime: '10 min',
  },
  {
    id: 'zero-trust',
    title: 'Zero Trust Architecture Designer',
    description: 'Design a Zero Trust architecture by identifying trust boundaries, configuring micro-segmentation, and implementing continuous verification.',
    difficulty: 5,
    category: 'CASP+',
    tags: ['zero-trust', 'architecture', 'micro-segmentation'],
    xpReward: 70,
    estimatedTime: '12 min',
  },
  {
    id: 'cloud-migration-sec',
    title: 'Cloud Migration Security Assessment',
    description: 'Evaluate security considerations for cloud migration including data classification, encryption, identity federation, and shared responsibility.',
    difficulty: 4,
    category: 'CASP+',
    tags: ['cloud-security', 'migration', 'encryption', 'identity-federation'],
    xpReward: 60,
    estimatedTime: '10 min',
  },
  {
    id: 'pki-infra',
    title: 'PKI Infrastructure Designer',
    description: 'Design a PKI infrastructure including CA hierarchy, certificate templates, revocation mechanisms, key management, and audit procedures.',
    difficulty: 5,
    category: 'CASP+',
    tags: ['pki', 'certificates', 'ca-hierarchy', 'key-management'],
    xpReward: 70,
    estimatedTime: '12 min',
  },
  {
    id: 'bcp-dr-planner',
    title: 'BCP/DR Planner',
    description: 'Design business continuity and disaster recovery plans including BIA, RTO/RPO calculations, failover design, and recovery testing.',
    difficulty: 4,
    category: 'CASP+',
    tags: ['bcp', 'disaster-recovery', 'rto', 'rpo', 'business-continuity'],
    xpReward: 60,
    estimatedTime: '10 min',
  },
  {
    id: 'sec-arch-review',
    title: 'Security Architecture Review',
    description: 'Review security architectures to identify vulnerabilities, validate compliance, assess defense-in-depth, and review network segmentation.',
    difficulty: 5,
    category: 'CASP+',
    tags: ['architecture', 'review', 'defense-in-depth', 'compliance'],
    xpReward: 70,
    estimatedTime: '12 min',
  },
  // ── Cloud+ PBQs ──
  {
    id: 'iam-policy',
    title: 'IAM Policy Builder',
    description: 'Build least-privilege IAM policies, configure role assumptions, set up MFA, implement SCPs, and audit permissions.',
    difficulty: 4,
    category: 'Cloud+',
    tags: ['iam', 'policy', 'least-privilege', 'mfa', 'scp'],
    xpReward: 60,
    estimatedTime: '10 min',
  },
  {
    id: 'vpc-designer',
    title: 'VPC Network Designer',
    description: 'Design a VPC with proper subnet layout, route tables, NACLs, security groups, and VPC peering configurations.',
    difficulty: 4,
    category: 'Cloud+',
    tags: ['vpc', 'subnets', 'nacl', 'security-groups', 'peering'],
    xpReward: 60,
    estimatedTime: '10 min',
  },
  {
    id: 'container-sec',
    title: 'Container Security',
    description: 'Secure container environments by scanning images, configuring runtime security, implementing network policies, and managing secrets.',
    difficulty: 3,
    category: 'Cloud+',
    tags: ['containers', 'kubernetes', 'docker', 'runtime-security'],
    xpReward: 50,
    estimatedTime: '10 min',
  },
  {
    id: 'cloud-storage',
    title: 'Cloud Storage Security',
    description: 'Secure cloud storage by configuring bucket policies, encryption, lifecycle rules, access logging, and versioning.',
    difficulty: 3,
    category: 'Cloud+',
    tags: ['cloud-storage', 's3', 'encryption', 'bucket-policy'],
    xpReward: 50,
    estimatedTime: '10 min',
  },
  {
    id: 'load-balancer',
    title: 'Load Balancer Configuration',
    description: 'Configure load balancers including type selection, health checks, SSL termination, sticky sessions, and auto-scaling integration.',
    difficulty: 3,
    category: 'Cloud+',
    tags: ['load-balancer', 'ssl', 'health-checks', 'auto-scaling'],
    xpReward: 50,
    estimatedTime: '10 min',
  },
  {
    id: 'cloud-monitor',
    title: 'Cloud Monitoring',
    description: 'Configure cloud monitoring including alerts, log aggregation, dashboards, anomaly detection, and audit trails.',
    difficulty: 3,
    category: 'Cloud+',
    tags: ['monitoring', 'alerting', 'logging', 'anomaly-detection'],
    xpReward: 50,
    estimatedTime: '10 min',
  },
];

export const CATEGORY_CONFIG: Record<string, { color: string; icon: string }> = {
  'PenTest+': { color: '#ff3366', icon: 'Target' },
  'Security+': { color: '#00ff41', icon: 'Shield' },
  'Network+': { color: '#00d4ff', icon: 'Network' },
  'A+': { color: '#2ec4b6', icon: 'Cpu' },
  'Linux LPI-1': { color: '#fb8500', icon: 'Terminal' },
  'Linux+': { color: '#ff9500', icon: 'Monitor' },
  'CySA+': { color: '#e63946', icon: 'Search' },
  'CASP+': { color: '#06d6a0', icon: 'Building' },
  'Cloud+': { color: '#00b4d8', icon: 'Cloud' },
};

export const PBQ_ACCENT_COLORS: Record<string, string> = {
  'network-topology': '#00d4ff',
  'terminal-sim': '#00ff41',
  'web-vuln-hotspot': '#a855f7',
  'firewall-rules': '#ffaa00',
  'cert-chain': '#00d4ff',
  'log-radar': '#ff3366',
  'wireless-attack': '#00e5ff',
  'exploit-chain': '#ff3366',
  'sql-injection': '#ff3366',
  'social-engineering': '#ff3366',
  'incident-response': '#00ff41',
  'access-control': '#00ff41',
  'subnet-calculator': '#00d4ff',
  'protocol-analyzer': '#00d4ff',
  'dns-resolution': '#00d4ff',
  'vlan-config': '#00d4ff',
  'cable-tester': '#00d4ff',
  'routing-table': '#00d4ff',
  // A+
  'hardware-diag': '#2ec4b6',
  'os-troubleshoot': '#2ec4b6',
  'bios-config': '#2ec4b6',
  'disk-management': '#2ec4b6',
  'mobile-repair': '#2ec4b6',
  'print-troubleshoot': '#2ec4b6',
  // LPI-1
  'file-permissions': '#fb8500',
  'package-manager': '#fb8500',
  'process-manager': '#fb8500',
  'shell-script': '#fb8500',
  'user-management': '#fb8500',
  'system-logs': '#fb8500',
  // Linux+
  'kernel-module': '#ff9500',
  'lvm-storage': '#ff9500',
  'systemd-service': '#ff9500',
  'linux-firewall': '#ff9500',
  'container-lab': '#ff9500',
  'linux-network-config': '#ff9500',
  // CySA+
  'siem-dashboard': '#e63946',
  'threat-intel': '#e63946',
  'malware-analysis': '#e63946',
  'vuln-scanner': '#e63946',
  'ir-timeline': '#e63946',
  'forensics': '#e63946',
  // CASP+
  'risk-matrix': '#06d6a0',
  'zero-trust': '#06d6a0',
  'cloud-migration-sec': '#06d6a0',
  'pki-infra': '#06d6a0',
  'bcp-dr-planner': '#06d6a0',
  'sec-arch-review': '#06d6a0',
  // Cloud+
  'iam-policy': '#00b4d8',
  'vpc-designer': '#00b4d8',
  'container-sec': '#00b4d8',
  'cloud-storage': '#00b4d8',
  'load-balancer': '#00b4d8',
  'cloud-monitor': '#00b4d8',
};

export const PBQ_ICONS: Record<string, string> = {
  'network-topology': 'Network',
  'terminal-sim': 'Terminal',
  'web-vuln-hotspot': 'Globe',
  'firewall-rules': 'ShieldCheck',
  'cert-chain': 'Lock',
  'log-radar': 'Activity',
  'wireless-attack': 'Wifi',
  'exploit-chain': 'Target',
  'sql-injection': 'Database',
  'social-engineering': 'Mail',
  'incident-response': 'AlertTriangle',
  'access-control': 'Key',
  'subnet-calculator': 'Calculator',
  'protocol-analyzer': 'Search',
  'dns-resolution': 'Globe',
  'vlan-config': 'Layers',
  'cable-tester': 'Cable',
  'routing-table': 'GitBranch',
  // A+
  'hardware-diag': 'Cpu',
  'os-troubleshoot': 'Monitor',
  'bios-config': 'Settings',
  'disk-management': 'HardDrive',
  'mobile-repair': 'Smartphone',
  'print-troubleshoot': 'Printer',
  // LPI-1
  'file-permissions': 'Lock',
  'package-manager': 'Package',
  'process-manager': 'Activity',
  'shell-script': 'Terminal',
  'user-management': 'Users',
  'system-logs': 'FileText',
  // Linux+
  'kernel-module': 'Cpu',
  'lvm-storage': 'HardDrive',
  'systemd-service': 'Settings',
  'linux-firewall': 'Shield',
  'container-lab': 'Container',
  'linux-network-config': 'Network',
  // CySA+
  'siem-dashboard': 'BarChart3',
  'threat-intel': 'Crosshair',
  'malware-analysis': 'Bug',
  'vuln-scanner': 'Scan',
  'ir-timeline': 'Clock',
  'forensics': 'Search',
  // CASP+
  'risk-matrix': 'BarChart3',
  'zero-trust': 'ShieldCheck',
  'cloud-migration-sec': 'Cloud',
  'pki-infra': 'Lock',
  'bcp-dr-planner': 'Shield',
  'sec-arch-review': 'Eye',
  // Cloud+
  'iam-policy': 'Users',
  'vpc-designer': 'Network',
  'container-sec': 'Box',
  'cloud-storage': 'Database',
  'load-balancer': 'ArrowUpDown',
  'cloud-monitor': 'Activity',
};
